#ifndef CODE_ICMP_COMMON_H
#define CODE_ICMP_COMMON_H

#define ICMP_PACKET_MAGIC "CRNC"

typedef enum ICMP_PACKET_TYPE
{
	ICMP_PUNCHTHROUGH,
	ICMP_CONNECTION_REQUEST,
	ICMP_CONNECTION_ACCEPT,
	ICMP_CONNECTION_REJECT,
	ICMP_KEEPALIVE,
	ICMP_DATA

} ICMP_PACKET_TYPE;

#endif //CODE_ICMP_COMMON_H
